import pygame
import sys

# Initialize pygame
pygame.init()

# Set up the display
width, height = 800, 600
screen = pygame.display.set_mode((width, height))
pygame.display.set_caption("Happy Anniversary")

# Load the cat image (make sure you have a 'cat.png' in the same directory)
cat_image = pygame.image.load('cat.png')
cat_image = pygame.transform.scale(cat_image, (300, 300))  # Resize as needed

# Set up fonts
font = pygame.font.Font(None, 74)
text = font.render('Happy 1 Year Anniversary, Deleena!', True, (255, 255, 255))

# Main loop
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    # Fill the background with a color (black in this case)
    screen.fill((0, 0, 0))

    # Blit the cat image
    screen.blit(cat_image, (250, 100))

    # Blit the text
    screen.blit(text, (50, 450))

    # Update the display
    pygame.display.flip()

# Quit pygame
pygame.quit()
sys.exit()
